spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipeapi
    username: recipesUser
    password: recipesPass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    h2:
      console:
        enabled: true
