spring:
  config:
    import: optional:file:prod.env[.properties]
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/recipes?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

server:
  shutdown: graceful
  compression:
    enabled: true

application:
  api-key: ${APPLICATION_API_KEY}
