spring:
  config:
    import: optional:file:dev.env[.properties]
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipeapi
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    h2:
      console:
        enabled: true

logging:
  level:
    root: debug

application:
  api-key: ${APPLICATION_API_KEY}
