spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipeapi
    username: recipesUser
    password: recipesPass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    h2:
      console:
        enabled: true

logging:
  level:
    root: debug

application:
  api-key: '8ba20537-61f2-4ccd-a796-39478a6149a7'
